### ISSUE TITLE
ci: use tox for testing

### ISSUE THREAD

**Issue by MartinBernstorff** [MartinBernstorff/swift-python-cookiecutter#115]
Would allow for the full test suite to be run locally. Specifically:
1. tox checks if there are new dependencies. If so, installs them. This means that if we add a new dependency, but forget to add it to the `.toml`, we'll catch it locally. (I make this mistake too frequently :-()
2. Local testing across python versions, or for a specific python version

Implementaiton-wise, I think we should have: run in the current environment by default, and then:
* `inv pr` - run in selected environments
* `inv test` - run in activated `.venv`. Only run in tox environments if specified (kwarg flag which takes which python versions to run in). 

https://tox.wiki/en/latest/user_guide.html

![](https://tox.wiki/en/latest/_images/overview_light.svg)

Should be pretty easy to set up. What do you think? @KennethEnevoldsen :-)

**Comment by KennethEnevoldsen** [comment]
- Seems like 1 might be solvable in other ways (so if that is the main problem I think we should explore those as well)
- 2: what happens if I install a package to test, but I don't want to actually use it, will that raise an error?
- 3: I have rarely had issues because of this after we changed to 3.9, but I see that it might be nice (always nice to move CI closer local workflow)

Have you tried it out yet? I am unsure if the additional complexity is worth it if it only 1) that we want to solve

**Comment by MartinBernstorff** [comment]
> tox checks if there are new dependencies. If so, installs them. This means that if we add a new dependency, but forget to add it to the .toml, we'll catch it locally. (I make this mistake too frequently :-()
How else would you check this locally? :-)

> What happens if I install a package to test, but I don't want to actually use it, will that raise an error?
I'm not sure what you mean? tox updates the test-env to match the current .toml.

> I have rarely had issues because of this after we changed to 3.9, but I see that it might be nice (always nice to move CI closer local workflow)
Agreed on both counts.

Haven't tested it out yet, just wanted to get your input at a conceptual level first. My impression is that tox is very much production ready, so I think the experienced complexity will be pretty small. Will give it a go the next time I run into problems 👍
