### ISSUE TITLE
task.py assumes Martin style virtual environments

### ISSUE THREAD

**Issue by KennethEnevoldsen** [MartinBernstorff/swift-python-cookiecutter#71]
Seems like there are quite a few assumptions in the invoke-command which I feel might be problematic for general usage (or use by me ;) ).

So here is some pointers:
- It seems like the invoke file assumes both the python version to be 3.9? (I don't see a good fix to this though)
- It seems like venv is created within the environment, actually fine with this, but it should not create it if I am already in an environment

**Comment by MartinBernstorff** [comment]
> * It seems like the invoke file assumes both the python version to be 3.9? (I don't see a good fix to this though)

It takes --python-version as a `kwarg`, so you can specify which version you want, as long as it's under your path as `python{version}` :-)

> * It seems like venv is created within the environment, actually fine with this, but it should not create it if I am already in an environment

Uncertain about what "within the environment" means in this context. My understanding is that whether you have an environment activated or not at the time you run `setup_venv` shouldn't matter, since the virtual environment is based on the file system, not the current shell context.

For the file system, `if not Path(venv_name).exists():` should guard against creating environments if an "appropriately named" environment already exists. 

That said, we could glob for `\..*venv.*39` or similar. 

![image](https://user-images.githubusercontent.com/8526086/229713611-d0e38542-631c-4ec8-b16e-51cced4c6b39.png)

**Comment by KennethEnevoldsen** [comment]
> It takes --python-version as a kwarg, so you can specify which version you want, as long as it's under your path as python{version} :-)

I noticed it just doesn't seem like the best default behaviour to just assume a python version

Uncertain about what "within the en

> vironment" means in this context. My understanding is that whether you have an environment activated or not at the time you run setup_venv shouldn't matter, since the virtual environment is based on the file system, not the current shell context.
> 
> For the file system, if not Path(venv_name).exists(): should guard against creating environments if an "appropriately named" environment already exists.

That assumes both that you have your virtualenvironment in your project environment and the name  (poetry check the current instance you are in)

> In general, I think being at least a little opinionated about venvs is necessary, but super open to refining those opinions!

That is what this thread is here for. Wanted to see what people suggest. I e.g. looked at this [StackOverflow](https://stackoverflow.com/questions/12184846/where-should-virtualenvs-be-created) (first in search no selection). It seems like there is three reasons to not have the virtual environment in the project folder:

1) it is system specific
2) you risk accidentally distributing it
3) it prevents you from moving the repository

In the big scheme of things however, I did not see lot of strong opinions of this. I would be fine if it just assumed my current environment if I am in an environment. For now I just completely ignore the setup commands.

**Comment by KennethEnevoldsen** [comment]
So at least some of the stuff (e.g. the docs) are quite nice, it is basically an alternative to the FAQ, but I would probably prefer it minimal. So if I were to choose I would probably remove all github cli parts - but I don't have a strong preference with it being there or not - the benefit of collaboration probably outweigh the (rather minor) preference

**Comment by MartinBernstorff** [comment]
> 1. it is system specific
> 2. you risk accidentally distributing it
> 3. it prevents you from moving the repository

1. Agreed, that's why it's included in the `.gitignore`.
2. Not too worried about that, see 1.
3. Not sure I understand this point?

> So at least some of the stuff (e.g. the docs) are quite nice, it is basically an alternative to the FAQ, but I would probably prefer it minimal. So if I were to choose I would probably remove all github cli parts - but I don't have a strong preference with it being there or not - the benefit of collaboration probably outweigh the (rather minor) preference

Yeah, I agree! It's really nice to abstract away the commands that are very project specific, so you don't have to remember them across projects.

I'm super open to modifications - especially since creating my own CLI would be so easy (thanks a tonne for the suggestion!).

**Comment by KennethEnevoldsen** [comment]
1, 2) yea that the probably why there are no big opinions on this.

3) if you move the project folder it can (will?) break dependencies in the python environment.

> I'm super open to modifications - especially since creating my own CLI would be so easy (thanks a tonne for the suggestion!).

If so it is maybe ideal to just discuss which should be there and then remove the rest:

I would argue for:

```
lint
docs
setup # could be left out, but I don't mind it, this should probably install as well?
install
test
update
```

**Comment by MartinBernstorff** [comment]
> I'm super open to modifications - especially since creating my own CLI would be so easy (thanks a tonne for the suggestion!).

Ah, so we'd only be removing the `pr @task`? In that case, it seems the added complexity of me adding a CLI is not worth the decrease in complexity we get here :-)

**Comment by KennethEnevoldsen** [comment]
Yea at least for now. Might be if you wish to add more things.

**Comment by MartinBernstorff** [comment]
Agreed! Closing this for now, feel free to reopen or add a new issue if anything comes to mind.
